require_relative "./config/environment"
# gives us access to active record rake tasks
require 'sinatra/activerecord/rake'
# in console run the command $ rake -T
# to see all rake methods we can use

desc "Open console"
task :console do
  # prints out SQL queries to the console
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  Pry.start
end